#define WIN_FGC     CYAN    /* general fgc */
#define WIN_BGC     BLACK
#define TITLE_FGC   LTWHITE /* title block */
#define TITLE_BGC   BROWN
#define TITLE_EDGE  YELLOW  /* title block border fgc only */
#define BACK_G_FGC  BLUE    /* background */
#define BACK_G_BGC  BLACK
#define SHADOW_FGC  GREY    /* shadow attributes */
#define SHADOW_BGC  BLACK
#define HILITE_FGC  LTWHITE /* hilite colour for letters in menus */
#define HILITE_BGC  BLACK
#define HIL_OFF_FGC CYAN    /* normal colour for letters..same as WIN_FGC */
#define HIL_OFF_BGC BLACK
#define ERROR_FGC   LTWHITE /* error window */
#define ERROR_BGC   RED
#define MESSAGE_FGC MAGENTA /* messages */
#define MESSAGE_BGC BLACK
#define RUSURE_FGC  LTWHITE /* are you sure ?  question */
#define RUSURE_BGC  RED
#define HELP_FGC    BLACK   /* help messages */
#define HELP_BGC    GREEN
#define BAR_FGC     YELLOW  /* hilite bar colours */
#define BAR_BGC     MAGENTA

